# https://github.com/vercel/next.js/blob/canary/examples/with-docker-compose/docker-compose.dev.yml

version: '3'

services:
  medienhaus-dev-tools:
    container_name: medienhaus-dev-tools
    build:
      context: .
      dockerfile: dev.Dockerfile
    #environment:
    #  ENV_VARIABLE: ${ENV_VARIABLE}
    #  NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    #env_file:
    #  - .env
    #volumes:
    #  - ./medienhaus-dev-tools/src:/app/src
    #  - ./medienhaus-dev-tools/public:/app/public
    restart: unless-stopped
    ports:
      - 3000:3000
    #networks:
    #  - medienhaus-dev-tools

#networks:
#  medienhaus-dev-tools:
#    driver: bridge
#    external: true
